### ============================================================================
### 1. REGISTER A NEW BAPTISM (THE START OF LIFE)
### ============================================================================
# Be sure to paste your actual St. Christopher Parish Secretary token below!
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZWNzdGNocmlzdG9waGVyQGRvbWFuc2Eub3JnIiwicm9sZSI6IlBhcmlzaCBTZWNyZXRhcnkiLCJwYXJpc2hfaWQiOjE3LCJkZWFuZXJ5X2lkIjo0LCJ0ZW5hbnRfc2NoZW1hIjoicGFyaXNoX3N0X2NocmlzdG9waGVyIiwic2Vzc2lvbl9pZCI6IjQ3NWM5NDYzLTg1MTEtNGIzMC04MmY1LWQ3MTc3MTJhYTQyMCIsImV4cCI6MTc3NDA3MDc5MX0.VS8uMFFIcCLS_WTnxxa8vgh7nUuJ-EQT-Pte0t0TW9g

POST http://192.168.18.9:8000/api/v1/baptisms/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "Elias",
  "last_name": "Phiri",
  "dob": "1950-02-14",
  "date_of_baptism": "1950-03-10",
  "minister_of_baptism": "Fr. Patrick",
  "father_first_name": "John",
  "father_last_name": "Phiri",
  "mother_first_name": "Mary",
  "mother_last_name": "Bwalya",
  "godparents": "Joseph Mulenga",
  "village": "Mansa Central",
  "center": "St. Christopher"
}

> {%
    // PyCharm will automatically grab the generated number and save it as a variable!
    // (If your baptisms router uses a different response key, just manually copy the number to step 2)
    client.global.set("bap_num", response.body.canonical_reference);
%}


### ============================================================================
### 2. REGISTER DEATH (THE TRIGGER EVENT)
### ============================================================================
POST http://192.168.18.9:8000/api/v1/deaths/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "Elias",
  "last_name": "Phiri",
  "baptism_number": "{{bap_num}}",
  "date_of_death": "2026-03-20",
  "date_of_burial": "2026-03-22",
  "place_of_burial": "Mansa Cemetery",
  "minister_of_rites": "Fr. Thomas",
  "received_last_rites": true
}


### ============================================================================
### 3. VERIFY THE TRIGGER WORKED (SEARCH LOCAL BAPTISMS)
### ============================================================================
# Check the JSON response payload here.
# "is_deceased" should now be automatically set to true!
GET http://192.168.18.9:8000/api/v1/baptisms/search?q={{bap_num}}
Authorization: Bearer {{token}}


### ============================================================================
### 4. VERIFY GLOBAL INDEXING (SEARCH CDOM INDEX)
### ============================================================================
# Elias should now show up globally as a DEATH record.
GET http://192.168.18.9:8000/api/v1/deaths/search?q=Elias
Authorization: Bearer {{token}}