"""Initial Master Architecture

Revision ID: f1f548b6a1bd
Revises: 
Create Date: 2026-03-25 05:46:16.338427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1f548b6a1bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baptisms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('village', sa.String(), nullable=False),
    sa.Column('father_first_name', sa.String(), nullable=False),
    sa.Column('father_last_name', sa.String(), nullable=False),
    sa.Column('mother_first_name', sa.String(), nullable=False),
    sa.Column('mother_last_name', sa.String(), nullable=False),
    sa.Column('godparents', sa.String(), nullable=False),
    sa.Column('date_of_baptism', sa.Date(), nullable=False),
    sa.Column('minister_of_baptism', sa.String(), nullable=False),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('formatted_number', sa.String(), nullable=False),
    sa.Column('is_deceased', sa.Boolean(), nullable=True),
    sa.Column('death_record_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baptisms_formatted_number'), 'baptisms', ['formatted_number'], unique=True)
    op.create_index(op.f('ix_baptisms_registry_year'), 'baptisms', ['registry_year'], unique=False)
    op.create_table('confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('confirmation_name', sa.String(), nullable=True),
    sa.Column('baptism_number', sa.String(), nullable=True),
    sa.Column('sponsor_name', sa.String(), nullable=False),
    sa.Column('confirmation_date', sa.Date(), nullable=False),
    sa.Column('minister', sa.String(), nullable=False),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('formatted_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmations_formatted_number'), 'confirmations', ['formatted_number'], unique=True)
    op.create_index(op.f('ix_confirmations_registry_year'), 'confirmations', ['registry_year'], unique=False)
    op.create_table('deaneries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deaneries_id'), 'deaneries', ['id'], unique=False)
    op.create_index(op.f('ix_deaneries_name'), 'deaneries', ['name'], unique=True)
    op.create_table('death_register',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=False),
    sa.Column('cause_of_death', sa.String(), nullable=True),
    sa.Column('cemetery', sa.String(), nullable=False),
    sa.Column('sacraments_received', sa.Boolean(), nullable=True),
    sa.Column('minister', sa.String(), nullable=False),
    sa.Column('baptism_number', sa.String(), nullable=True),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('formatted_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_death_register_formatted_number'), 'death_register', ['formatted_number'], unique=True)
    op.create_index(op.f('ix_death_register_registry_year'), 'death_register', ['registry_year'], unique=False)
    op.create_table('diocesan_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=True),
    sa.Column('fund_name', sa.String(), nullable=False),
    sa.Column('fund_type', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diocesan_contributions_reporting_year'), 'diocesan_contributions', ['reporting_year'], unique=False)
    op.create_table('first_communions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('baptism_number', sa.String(), nullable=True),
    sa.Column('communion_date', sa.Date(), nullable=False),
    sa.Column('minister', sa.String(), nullable=False),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('formatted_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_communions_formatted_number'), 'first_communions', ['formatted_number'], unique=True)
    op.create_index(op.f('ix_first_communions_registry_year'), 'first_communions', ['registry_year'], unique=False)
    op.create_table('marriages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('groom_first_name', sa.String(), nullable=False),
    sa.Column('groom_last_name', sa.String(), nullable=False),
    sa.Column('groom_baptism_number', sa.String(), nullable=True),
    sa.Column('groom_religion', sa.Enum('CATHOLIC', 'OTHER_CHRISTIAN', 'NON_CHRISTIAN', name='religioncategory'), nullable=False),
    sa.Column('bride_first_name', sa.String(), nullable=False),
    sa.Column('bride_last_name', sa.String(), nullable=False),
    sa.Column('bride_baptism_number', sa.String(), nullable=True),
    sa.Column('bride_religion', sa.Enum('CATHOLIC', 'OTHER_CHRISTIAN', 'NON_CHRISTIAN', name='religioncategory'), nullable=False),
    sa.Column('marriage_date', sa.Date(), nullable=False),
    sa.Column('minister', sa.String(), nullable=False),
    sa.Column('witness_1', sa.String(), nullable=False),
    sa.Column('witness_2', sa.String(), nullable=False),
    sa.Column('registry_year', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('formatted_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marriages_formatted_number'), 'marriages', ['formatted_number'], unique=True)
    op.create_index(op.f('ix_marriages_registry_year'), 'marriages', ['registry_year'], unique=False)
    op.create_table('parish_finances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recorded_by', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parish_finances_transaction_date'), 'parish_finances', ['transaction_date'], unique=False)
    op.create_table('pending_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('target_record_id', sa.String(), nullable=False),
    sa.Column('proposed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_status'), 'pending_actions', ['status'], unique=False)
    op.create_table('user_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('office', sa.String(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('deanery_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invitations_email'), 'user_invitations', ['email'], unique=True)
    op.create_index(op.f('ix_user_invitations_token'), 'user_invitations', ['token'], unique=True)
    op.create_table('youth_action_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('target_demographic', sa.String(), nullable=True),
    sa.Column('proposed_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pp_feedback', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youth_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('parent_guardian_name', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('village_center', sa.String(), nullable=False),
    sa.Column('is_baptised', sa.Boolean(), nullable=True),
    sa.Column('is_communicant', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('canonical_baptism_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_plan_communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('sender_role', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('recipient_role', sa.String(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['youth_action_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plan_communications_plan_id'), 'action_plan_communications', ['plan_id'], unique=False)
    op.create_table('parishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deanery_id', sa.Integer(), nullable=True),
    sa.Column('schema_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deanery_id'], ['deaneries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_name')
    )
    op.create_index(op.f('ix_parishes_deanery_id'), 'parishes', ['deanery_id'], unique=False)
    op.create_index(op.f('ix_parishes_id'), 'parishes', ['id'], unique=False)
    op.create_index(op.f('ix_parishes_name'), 'parishes', ['name'], unique=False)
    op.create_table('diocesan_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('parish_name', sa.String(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('total_baptisms_ytd', sa.Integer(), nullable=True),
    sa.Column('total_communions_ytd', sa.Integer(), nullable=True),
    sa.Column('total_confirmations_ytd', sa.Integer(), nullable=True),
    sa.Column('total_marriages_ytd', sa.Integer(), nullable=True),
    sa.Column('total_deaths_ytd', sa.Integer(), nullable=True),
    sa.Column('diocesan_contributions_target_ytd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('diocesan_contributions_actual_ytd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diocesan_analytics_parish_id'), 'diocesan_analytics', ['parish_id'], unique=False)
    op.create_index(op.f('ix_diocesan_analytics_reporting_year'), 'diocesan_analytics', ['reporting_year'], unique=False)
    op.create_table('global_registry_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('canonical_number', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_registry_index_canonical_number'), 'global_registry_index', ['canonical_number'], unique=False)
    op.create_index(op.f('ix_global_registry_index_parish_id'), 'global_registry_index', ['parish_id'], unique=False)
    op.create_index(op.f('ix_global_registry_index_record_type'), 'global_registry_index', ['record_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('office', sa.String(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('deanery_id', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deanery_id'], ['deaneries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deanery_id'), 'users', ['deanery_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_parish_id'), 'users', ['parish_id'], unique=False)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('target_record_id', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('previous_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_record_id'), 'audit_logs', ['target_record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_table'), 'audit_logs', ['target_table'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_table'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_parish_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deanery_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_global_registry_index_record_type'), table_name='global_registry_index')
    op.drop_index(op.f('ix_global_registry_index_parish_id'), table_name='global_registry_index')
    op.drop_index(op.f('ix_global_registry_index_canonical_number'), table_name='global_registry_index')
    op.drop_table('global_registry_index')
    op.drop_index(op.f('ix_diocesan_analytics_reporting_year'), table_name='diocesan_analytics')
    op.drop_index(op.f('ix_diocesan_analytics_parish_id'), table_name='diocesan_analytics')
    op.drop_table('diocesan_analytics')
    op.drop_index(op.f('ix_parishes_name'), table_name='parishes')
    op.drop_index(op.f('ix_parishes_id'), table_name='parishes')
    op.drop_index(op.f('ix_parishes_deanery_id'), table_name='parishes')
    op.drop_table('parishes')
    op.drop_index(op.f('ix_action_plan_communications_plan_id'), table_name='action_plan_communications')
    op.drop_table('action_plan_communications')
    op.drop_table('youth_profiles')
    op.drop_table('youth_action_plans')
    op.drop_index(op.f('ix_user_invitations_token'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_email'), table_name='user_invitations')
    op.drop_table('user_invitations')
    op.drop_index(op.f('ix_pending_actions_status'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_parish_finances_transaction_date'), table_name='parish_finances')
    op.drop_table('parish_finances')
    op.drop_index(op.f('ix_marriages_registry_year'), table_name='marriages')
    op.drop_index(op.f('ix_marriages_formatted_number'), table_name='marriages')
    op.drop_table('marriages')
    op.drop_index(op.f('ix_first_communions_registry_year'), table_name='first_communions')
    op.drop_index(op.f('ix_first_communions_formatted_number'), table_name='first_communions')
    op.drop_table('first_communions')
    op.drop_index(op.f('ix_diocesan_contributions_reporting_year'), table_name='diocesan_contributions')
    op.drop_table('diocesan_contributions')
    op.drop_index(op.f('ix_death_register_registry_year'), table_name='death_register')
    op.drop_index(op.f('ix_death_register_formatted_number'), table_name='death_register')
    op.drop_table('death_register')
    op.drop_index(op.f('ix_deaneries_name'), table_name='deaneries')
    op.drop_index(op.f('ix_deaneries_id'), table_name='deaneries')
    op.drop_table('deaneries')
    op.drop_index(op.f('ix_confirmations_registry_year'), table_name='confirmations')
    op.drop_index(op.f('ix_confirmations_formatted_number'), table_name='confirmations')
    op.drop_table('confirmations')
    op.drop_index(op.f('ix_baptisms_registry_year'), table_name='baptisms')
    op.drop_index(op.f('ix_baptisms_formatted_number'), table_name='baptisms')
    op.drop_table('baptisms')
    # ### end Alembic commands ###
